#!/bin/bash                                                                                                                                                                           

shntool conv -o flac "$1"
